### ISSUE TITLE
Install fails outh_listener

### ISSUE THREAD

**Issue by wbashir** [jdeboer/ganalytics#49]
I am having a difficult time getting this package to install using `devtools`. 

I keep getting the same error using the latest versions of R and Rstudio

```
oauth_listener() needs an interactive environment
```

Any help is appreciated as I was able to install other packages with `devtools:install_github()`

**Comment by jdeboer** [comment]
Hi @wbashir ,

It sounds like something to do with the authentication protocol, which is mostly handled through a package called `httr`. Are you using any other similar or related packages in R that might also use `httr`?

Would you be able to provide some more information about when you receive this error? Are you using the package within an R installed on your local machine or via a remote server? What is the environment you are running your script from?

Also, would you please provide a list of the commands and output you are seeing in R to help me pinpoint the issue for you?

Also, you can use the `httr::with_verbose()` function to get more diagnostics about requests that can sometimes help with working out the issue.

Hear from you soon.

Johann.

**Comment by wbashir** [comment]
** Are you using any other similar or related packages in R that might also use httr?**

Not that I know of, I am just trying to install this package but not sure of any dependencies within my environment. 

**Are you using the package within an R installed on your local machine or via a remote server? What is the environment you are running your script from?**

I am trying to install this package using R installing on a local machine with a script created in Rstudio.

**Also, would you please provide a list of the commands and output you are seeing in R to help me pinpoint the issue for you?**

````
Installing ganalytics
"C:/PROGRA~1/R/R-32~1.3/bin/x64/R" --no-site-file --no-environ --no-save --no-restore CMD INSTALL  \
  "C:/AppData/Local/Temp/RtmpkvgEGY/devtools198839b95fe9/jdeboer-ganalytics-388cc88"  \
  --library="\\My Documents/R/win-library/3.2" --install-tests 

* installing *source* package 'ganalytics' ...
** R
** demo
** inst
** tests
** preparing package for lazy loading
Error : oauth_listener() needs an interactive environment.
Error : unable to load R code in package 'ganalytics'
ERROR: lazy loading failed for package 'ganalytics'
* 
Error: Command failed (1)

````

As you can see I am unable to load the R code in this package.

**Comment by jdeboer** [comment]
Thank you @wbashir that is very helpful. I'll look into this and will get back to you.

**Comment by jdeboer** [comment]
Hi @wbashir hopefully I've found the issue. Could you please retry the installation and let me know if you continue to get the same error or if you encounter any other issues? Thanks.

**Comment by wbashir** [comment]
@jdeboer Thanks again for taking a look. I am still seeing the same error on a `Windows 7` machine. I will try this on another computer and see if my environment is causing any issues.

**Comment by jdeboer** [comment]
Hi @wbashir,

I am thinking that there might be a bug where the package is attempting to update its metadata file during installation. So I would like to see if another change I have made in the dev version of the package resolves the issue for you. You can install the dev version of the package with the following command in R:

```{r}
devtools::install_github("jdeboer/ganalytics", ref = "dev")
```

Please let me know how this goes. If it doesn't resolve the issue then I will try to make some time later next week to look into this in more depth and try to get to the bottom of it.

Something else you could try is creating and saving the auth token with `httr` prior to installation. There are a few steps to doing this, so I can take you through that if we get to that point.

Thanks for letting me know about the issue you are facing. I hope we can resolve this soon as it may be affecting other users too.

Kind regards,

Johann.

**Comment by wbashir** [comment]
@jdeboer 

Attempting to download the development version of this package
````
Downloading GitHub repo jdeboer/ganalytics@dev
from URL https://api.github.com/repos/jdeboer/ganalytics/zipball/dev
Installing ganalytics
````

The package isn't found with the stack trace below:
````
* installing *source* package 'ganalytics' ...
** R
** demo
** inst
** tests
** preparing package for lazy loading
Error : Path '' does not exist
Error : unable to load R code in package 'ganalytics'
ERROR: lazy loading failed for package 'ganalytics'
`````

Maybe I don't have `devtools' correct. I will try your `httr` suggestion as well

**Comment by jdeboer** [comment]
Thanks, that's really helpful, as it confirms what I think the issue might
be. Will look into it.

**Comment by jdeboer** [comment]
Hi @wbashir , could you please run the following command in R to check which version of devtools you have installed? It would be good to know as I might need to explicitly set a minimum version number in the analytics package dependencies:
```{r}
packageVersion("devtools")
```

Please let me know what output you get. You might then want to try installing the latest version of devtools using:
```{r}
install.packages("devtools")
```

Perhaps then you can retry the installation of ganalytics:
```{r}
devtools::install_github("jdeboer/ganalytics")
```

Thanks,

Johann.

**Comment by wbashir** [comment]
````
> packageVersion("devtools")
[1] ‘1.10.0’
````
I then reran the commands `install.packages("devtools")` and `devtools::install_github("jdeboer/ganalytics")` with the same error `outh_listener() needs an interactive environment`. I have read that this is sometimes due to 3.1.2 and Windows ?

**Comment by jdeboer** [comment]
From what I can tell, it seems that when the package is installing, one of the necessary datafiles is either not being added or for some other reason it cannot be found - I cannot figure why this is happening for you though, and I haven't been able to replicate this issue yet, may be need more details about your R environment and session information.

This datafile contains a list of the known Google Analytics dimensions and metrics. What appears to be happening is that an error occurs at the late stage of the installation process when the package is loaded to test that is has been installed. Because that datafile is not there, the package attempts to recreate that datafile by querying the Google Analytics metadata API for a complete list of dimensions and metrics. This is where the OAuth listener error occurs.

The package is using OAuth to access the metadata API and as part of the authorisation handshake, `httr` invokes a browser window where the user is requested permission to access the Metadata API, but this cannot be allowed because the installation process has not finished and therefore the user is not in an interactive session until that installation has completed.

I am now wondering if it might be possible to avoid the OAuth handshake for the metadata API, as I don't think any special access permissions are required. So this something perhaps I could look into. There are other ways we could try to address this as well, such as having a fall-back mechanism during installation.

1. You mentioned something about version 3.1.2 and Windows? Please share any further information you have and I'll have a look into it.

2. Would you please run the following in R to tell me about your environment and reply with the results?
```{r}
sessionInfo()
```

3. Just in case it helps, you could try the following parameters during installation to ensure that all dependencies are up to date and to do a clean install:
```{r}
devtools::install_github(
  "jdeboer/ganalytics",
  upgrade_dependencies = TRUE,
  local = TRUE,
  force = TRUE
)
```

Thank you very much for working with me in solving this.

**Comment by wbashir** [comment]
@jdeboer 

Sorry for the late response here but I tried your suggesting to install with dependencies and the output is below:

````
Installing ganalytics
Installing 1 package: munsell
package ‘munsell’ successfully unpacked and MD5 sums checked

* installing *source* package 'ganalytics' ...
** R
** demo
** inst
** tests
** preparing package for lazy loading
Error : oauth_listener() needs an interactive environment.
Error : unable to load R code in package 'ganalytics'
ERROR: lazy loading failed for package 'ganalytics'
````

It still failed :/ The `sessionInfo()` called is below:

`````
[1] stats     graphics  grDevices utils     datasets  methods   base     
loaded via a namespace (and not attached):
R version 3.2.3 (2015-12-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1
[1] httr_1.1.0      R6_2.1.2        tools_3.2.3     withr_1.0.1     curl_0.9.5      memoise_1.0.0   digest_0.6.9   
[8] devtools_1.10.0
`````
I hope that helps and gets us further.

**Comment by jdeboer** [comment]
Hi @wbashir 

Try installing `httpuv` prior to installation of `ganalytics`:
```{r}
install.packages("httpuv")
```

Please let me know how you go with the above instructions. I've got another plan if that doesn't work for you.

I think we're getting closer to finding the issue and a permanent fix, so thank you for helping out with this.

Regards,

Johann.

**Comment by jdeboer** [comment]
By the way, here's the other plan if the above doesn't work for you first:

Let's try a manual authentication prior to installation.

Please run this block of code, substituting for your Google Developers API project client ID and client secret. (Remember to keep those hidden):

```{r}
client_id <- "insert your client ID here"
client_secret <- "insert your client secret here"
```

Then run the following commands and let me know how it goes. If successful, then retry the installation of `ganalytics`. The idea is to have authentication already done and saved in the default location, so that `ganalytics` won't attempt to do that itself during installation:

```{r}
library(httr)
scope <- "https://www.googleapis.com/auth/analytics.readonly"
url <- "https://www.googleapis.com/analytics/v3/metadata/ga/columns"
endpoint <- oauth_endpoints(name = "google")
cache <- "~/.google_apis_auth.RDS"
app <- oauth_app(
  appname = "GOOGLE_APIS",
  key = client_id,
  secret = client_secret
)
token <- oauth2.0_token(
  endpoint = endpoint,
  app = app,
  scope = scope,
  use_oob = FALSE,
  as_header = TRUE,
  cache = cache
)
config = config(token = token)
GET(url = url, config = config)
```

**Comment by wbashir** [comment]
@jdeboer 

Ok so really wierd. I went through the authentication with `client_id` and `client_secret` set in my R session and the `GET` called worked returning me a 200 return code but still the same error upon installation.

**Comment by jdeboer** [comment]
Hi @wbashir . Just wanted to check whether you had any luck with this issue? I know it's been a long time! I haven't seen it appearing elsewhere and there's been no reports of anyone else having this problem, so I'm hoping that you were able to resolve this? Please let me know if you continue to see this error and I'll reopen this issue. Thanks.
