### ISSUE TITLE
Help for Expr()?

### ISSUE THREAD

**Issue by gilliganondata** [jdeboer/ganalytics#74]
When I type `?Expr()` I get a `no documentation for function 'Expr'` error. That _is_ a function in the package, right? Should it have documentation available?

**Comment by gilliganondata** [comment]
And... the same thing for `PerSession()`. No function documentation available?

**Comment by jdeboer** [comment]
Thanks for letting me know, I'll take a look.

**Comment by gilliganondata** [comment]
I was using the dev version, but I went back to the CRAN version. I also restarted R and, separately, restarted RStudio. The error persists.

*> ?Expr()*
```
Error in .helpForCall(topicExpr, parent.frame()) : 
  no documentation for function ‘Expr’ and signature ‘object = "missing", comparator = "missing", operand = "missing", metricScope = "character"’
In addition: Warning message:
In .helpForCall(topicExpr, parent.frame()) :
  no method defined for function ‘Expr’ and signature ‘object = "missing", comparator = "missing", operand = "missing", metricScope = "character"’
```

Does that help?

**Comment by jdeboer** [comment]
Hi @gilliganondata, Yes, that's very helpful. Instead of `?Expr()`, try `?Expr` and I think you won't see the error. Please let me know how that goes. I think the issue is related to the missing arguments in the call you are making to `Expr()`. I may need to make changes to the signatures defined in some of the S4 methods so as to match missing arguments to `Expr()`. I'm working on improvements to the documentation now, so this is good timing. If you come across any other issues, particularly with the documentation, please let me know. Thank you .
